worker_processes 4;

events {
    worker_connections 1024;
}

http {
    # Configuration containing list of application servers
    upstream app_servers {
        server ctfd:8000;
    }

    # Redirect all HTTP traffic to HTTPS
    server {
        listen 80;
        server_name localhost;

        # Redirects with a 301 (Moved Permanently) to the HTTPS version
        return 301 https://$host$request_uri;
    }

    # HTTPS Server Block
    server {
        listen 443 ssl;
        server_name localhost;

        # SSL Certificate Locations (inside the container)
        ssl_certificate /etc/nginx/ssl/server.crt;    # Since im doing it locally, i self-made the SSL cert. You should replace this cert with the right one during production
        ssl_certificate_key /etc/nginx/ssl/server.key;

        # Recommended SSL Settings
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        gzip on;
        client_max_body_size 4G;

        # === SECURITY HEADERS ===
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none';" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Frame-Options "DENY" always;
        
        # HSTS (Strict-Transport-Security): Forces browsers to only use HTTPS for 1 year
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # Handle Server Sent Events for Notifications
        location /events {
            proxy_pass http://app_servers;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
            # Tells CTFd the protocol used (HTTPS)
            proxy_set_header X-Forwarded-Proto $scheme; 
        }

        # Proxy connections to the application servers
        location / {
            proxy_pass http://app_servers;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $server_name;
            # Tells CTFd the protocol used (HTTPS)
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
